ループを使う

diff --git a/.github/workflows/node.yml b/.github/workflows/node.yml
--- a/.github/workflows/node.yml
+++ b/.github/workflows/node.yml
@@ -22,6 +22,10 @@ jobs:
 
     # node --check で構文チェックのみ行う
     - run: |
-        set -e
-        find ${{ inputs.working-directory }} -name "*.js" -exec node --check {} \;
-      shell: bash
+        find ${{ inputs.working-directory }} -name "*.js" | while read -r file; do
+          echo "Checking $file"
+          if ! node --check "$file"; then
+            echo "Syntax error in $file"
+            exit 1
+          fi
+        done
